namespace CodexUsageMonitor;

internal static class LocalizationManager
{
    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["LocAppTitle"] = "Codex 用量",
        ["LocTrayMenuTitle"] = "Codex 用量菜单",
        ["LocMinimizeTooltip"] = "最小化到托盘",
        ["LocRefreshTooltip"] = "刷新数据",
        ["LocSettings"] = "设置",
        ["LocUpdateAvailable"] = "有新更新",
        ["LocAutomaticUpdateChecks"] = "自动检查更新",
        ["LocAutomaticUpdateChecksTooltip"] = "每天最多访问一次 GitHub Release 接口",
        ["LocCheckForUpdates"] = "检查更新",
        ["LocNewVersionPublished"] = "新版本已发布",
        ["LocViewUpdate"] = "查看更新",
        ["LocRemindLater"] = "稍后提醒",
        ["LocClose"] = "关闭",
        ["LocOverview"] = "总览",
        ["LocModels"] = "模型",
        ["LocHistory"] = "历史",
        ["LocLocalFirst"] = "本地优先",
        ["LocFooterStatus"] = "本地优先 · 每 15 分钟自动刷新 · 价格启动时校准",
        ["LocAutoRefresh"] = "每 15 分钟自动刷新",
        ["LocPricingCalibrated"] = "价格每次启动校准",
        ["LocOpenDataFolder"] = "打开数据目录",
        ["LocData"] = "数据",
        ["LocQuitApplication"] = "退出应用",
        ["LocQuit"] = "退出",
        ["LocAppearance"] = "外观",
        ["LocLight"] = "浅色",
        ["LocDark"] = "深色",
        ["LocStartup"] = "开机自动启动（后台运行）",
        ["LocStartupTooltip"] = "登录 Windows 后在托盘后台启动",
        ["LocLanguage"] = "语言",
        ["LocChinese"] = "中文",
        ["LocEnglish"] = "English",
        ["LocWeeklyRemaining"] = "本周剩余",
        ["LocQuotaPace"] = "额度节奏",
        ["LocGeneralFiveHour"] = "5 小时额度",
        ["LocDay1"] = "第1天",
        ["LocDay2"] = "第2天",
        ["LocDay3"] = "第3天",
        ["LocDay4"] = "第4天",
        ["LocDay5"] = "第5天",
        ["LocDay6"] = "第6天",
        ["LocDay7"] = "第7天",
        ["LocSparkLimit"] = "Codex Spark 限额",
        ["LocFiveHourWindow"] = "5 小时窗口",
        ["LocWeeklyWindow"] = "每周窗口",
        ["LocResetCards"] = "重置卡",
        ["LocMonthlyPricedCost"] = "本月已定价模型成本",
        ["LocCacheHit"] = "缓存命中",
        ["LocMonthlyComposition"] = "Token 组成 · 本月",
        ["LocUncached"] = "非缓存",
        ["LocCached"] = "缓存",
        ["LocOutput"] = "输出",
        ["LocReasoning"] = "推理",
        ["LocModelUsage"] = "模型用量",
        ["LocModelUsageDescription"] = "按本地 rollout 聚合模型、缓存与 API 等价成本",
        ["LocToday"] = "今天",
        ["Loc7Days"] = "7 天",
        ["Loc30Days"] = "30 天",
        ["LocPricedModelCost"] = "已定价模型成本",
        ["LocInputTokens"] = "输入 Tokens",
        ["LocModelRanking"] = "模型排行",
        ["LocNoModelUsage"] = "这个时间段还没有本地模型用量。",
        ["LocUsageComposition"] = "用量组成",
        ["LocHistoryTrends"] = "历史趋势",
        ["LocHistoryDescription"] = "本地 SQLite 历史与 Codex 官方日趋势",
        ["LocMonthlyTokens"] = "本月 Tokens",
        ["LocApiEquivalentCost"] = "API 等价成本",
        ["LocDailyTokens"] = "本月每日 Token",
        ["LocDailyTokensDescription"] = "日总量来自 account/usage/read；模型与缓存拆分来自本地 rollout。",
        ["LocHistoryPortable"] = "历史会随每次刷新写入本地数据库，换机时复制数据目录即可保留趋势。",
        ["LocOpenLocalDataFolder"] = "打开本地数据目录",
        ["LocDataFolderDescription"] = "数据库、价格快照与设置都保存在这里",
        ["LocBackOverview"] = "返回总览",
        ["LocBack"] = "返回",
        ["LocResetDetails"] = "重置卡详情",
        ["LocTimesAvailable"] = "次可用",
        ["LocValidityProgress"] = "有效期进度",
        ["LocGranted"] = "授予",
        ["LocCurrent"] = "当前",
        ["LocExpires"] = "到期",
        ["LocAvailableResetCards"] = "可用重置卡",
        ["LocResetHistory"] = "历史记录",
        ["LocResetHistoryDescription"] = "从首次运行开始记录；服务端缺少单卡详情时，使用与过期会标记为推测。",
        ["LocExpiryReminder"] = "到期前提醒",
        ["LocOpenCodexUsage"] = "打开 Codex 用量页面",
        ["LocOpenPanel"] = "打开面板",
        ["LocOpenPanelTooltip"] = "打开用量面板",
        ["LocRefreshNow"] = "立即刷新",
        ["LocRefreshNowTooltip"] = "立即刷新数据"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["LocAppTitle"] = "Codex Usage",
        ["LocTrayMenuTitle"] = "Codex Usage menu",
        ["LocMinimizeTooltip"] = "Minimize to tray",
        ["LocRefreshTooltip"] = "Refresh data",
        ["LocSettings"] = "Settings",
        ["LocUpdateAvailable"] = "Update available",
        ["LocAutomaticUpdateChecks"] = "Automatically check for updates",
        ["LocAutomaticUpdateChecksTooltip"] = "Checks GitHub Releases at most once per day",
        ["LocCheckForUpdates"] = "Check for updates",
        ["LocNewVersionPublished"] = "A new version is available",
        ["LocViewUpdate"] = "View update",
        ["LocRemindLater"] = "Remind me later",
        ["LocClose"] = "Close",
        ["LocOverview"] = "Overview",
        ["LocModels"] = "Models",
        ["LocHistory"] = "History",
        ["LocLocalFirst"] = "Local first",
        ["LocFooterStatus"] = "Local · 15 min auto-refresh · Prices checked at launch",
        ["LocAutoRefresh"] = "Refreshes every 15 minutes",
        ["LocPricingCalibrated"] = "Prices checked at startup",
        ["LocOpenDataFolder"] = "Open data folder",
        ["LocData"] = "Data",
        ["LocQuitApplication"] = "Quit application",
        ["LocQuit"] = "Quit",
        ["LocAppearance"] = "Appearance",
        ["LocLight"] = "Light",
        ["LocDark"] = "Dark",
        ["LocStartup"] = "Start with Windows",
        ["LocStartupTooltip"] = "Start in the tray after signing in to Windows",
        ["LocLanguage"] = "Language",
        ["LocChinese"] = "中文",
        ["LocEnglish"] = "English",
        ["LocWeeklyRemaining"] = "Weekly remaining",
        ["LocQuotaPace"] = "Quota pace",
        ["LocGeneralFiveHour"] = "5-hour quota",
        ["LocDay1"] = "Day 1",
        ["LocDay2"] = "Day 2",
        ["LocDay3"] = "Day 3",
        ["LocDay4"] = "Day 4",
        ["LocDay5"] = "Day 5",
        ["LocDay6"] = "Day 6",
        ["LocDay7"] = "Day 7",
        ["LocSparkLimit"] = "Codex Spark limits",
        ["LocFiveHourWindow"] = "5-hour window",
        ["LocWeeklyWindow"] = "Weekly window",
        ["LocResetCards"] = "Reset credits",
        ["LocMonthlyPricedCost"] = "Priced model cost this month",
        ["LocCacheHit"] = "Cache hit",
        ["LocMonthlyComposition"] = "Token composition · This month",
        ["LocUncached"] = "Uncached",
        ["LocCached"] = "Cached",
        ["LocOutput"] = "Output",
        ["LocReasoning"] = "Reasoning",
        ["LocModelUsage"] = "Model usage",
        ["LocModelUsageDescription"] = "Models, caching, and API-equivalent cost from local rollouts",
        ["LocToday"] = "Today",
        ["Loc7Days"] = "7 days",
        ["Loc30Days"] = "30 days",
        ["LocPricedModelCost"] = "Priced model cost",
        ["LocInputTokens"] = "Input tokens",
        ["LocModelRanking"] = "Model ranking",
        ["LocNoModelUsage"] = "No local model usage in this period.",
        ["LocUsageComposition"] = "Usage composition",
        ["LocHistoryTrends"] = "Usage history",
        ["LocHistoryDescription"] = "Local SQLite history and official Codex daily trends",
        ["LocMonthlyTokens"] = "Tokens this month",
        ["LocApiEquivalentCost"] = "API-equivalent cost",
        ["LocDailyTokens"] = "Daily tokens this month",
        ["LocDailyTokensDescription"] = "Daily totals come from account/usage/read; model and cache details come from local rollouts.",
        ["LocHistoryPortable"] = "Each refresh writes history to the local database. Copy the data folder to keep it when moving PCs.",
        ["LocOpenLocalDataFolder"] = "Open local data folder",
        ["LocDataFolderDescription"] = "Database, price snapshot, and settings are stored here",
        ["LocBackOverview"] = "Back to overview",
        ["LocBack"] = "Back",
        ["LocResetDetails"] = "Reset credit details",
        ["LocTimesAvailable"] = "available",
        ["LocValidityProgress"] = "Validity progress",
        ["LocGranted"] = "Granted",
        ["LocCurrent"] = "Now",
        ["LocExpires"] = "Expires",
        ["LocAvailableResetCards"] = "Available reset credits",
        ["LocResetHistory"] = "History",
        ["LocResetHistoryDescription"] = "Recorded from first run. Inferred use or expiry is marked when card details are unavailable.",
        ["LocExpiryReminder"] = "Expiry reminders",
        ["LocOpenCodexUsage"] = "Open Codex usage page",
        ["LocOpenPanel"] = "Open panel",
        ["LocOpenPanelTooltip"] = "Open usage panel",
        ["LocRefreshNow"] = "Refresh now",
        ["LocRefreshNowTooltip"] = "Refresh data now"
    };

    public static bool IsEnglish { get; private set; }

    public static string Get(string key, bool? isEnglish = null)
    {
        var source = (isEnglish ?? IsEnglish) ? English : Chinese;
        return source.TryGetValue(key, out var value) ? value : key;
    }

    public static void Apply(bool isEnglish)
    {
        IsEnglish = isEnglish;
        if (System.Windows.Application.Current is null)
        {
            return;
        }

        foreach (var (key, value) in isEnglish ? English : Chinese)
        {
            System.Windows.Application.Current.Resources[key] = value;
        }
    }
}
