namespace CodexUsageMonitor;

internal static class LocalizationManager
{
    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["LocAppTitle"] = "Codex 用量",
        ["LocTrayMenuTitle"] = "Codex 用量菜单",
        ["LocMinimizeTooltip"] = "最小化到托盘",
        ["LocRefreshTooltip"] = "刷新数据",
        ["LocSettings"] = "设置",
        ["LocUpdateAvailable"] = "有新更新",
        ["LocUpdateNow"] = "查看更新",
        ["LocAutomaticUpdateChecks"] = "自动检查更新",
        ["LocAutomaticUpdateChecksTooltip"] = "每天最多访问一次 GitHub Release 接口",
        ["LocCheckForUpdates"] = "检查更新",
        ["LocNewVersionPublished"] = "新版本已发布",
        ["LocViewUpdate"] = "查看更新",
        ["LocRemindLater"] = "稍后提醒",
        ["LocClose"] = "关闭",
        ["LocOverview"] = "总览",
        ["LocModels"] = "模型",
        ["LocHistory"] = "历史",
        ["LocLocalFirst"] = "本地优先",
        ["LocFooterStatus"] = "官方总量 · 本地存储 · 每 15 分钟刷新",
        ["LocCurrentVersion"] = "当前版本",
        ["LocAutoRefresh"] = "每 15 分钟自动刷新",
        ["LocPricingCalibrated"] = "价格每次启动校准",
        ["LocOpenDataFolder"] = "打开数据目录",
        ["LocData"] = "数据",
        ["LocQuitApplication"] = "退出应用",
        ["LocQuit"] = "退出",
        ["LocAppearance"] = "外观",
        ["LocLight"] = "浅色",
        ["LocDark"] = "深色",
        ["LocStartup"] = "开机自动启动（后台运行）",
        ["LocStartupTooltip"] = "登录 Windows 后在托盘后台启动",
        ["LocLanguage"] = "语言",
        ["LocChinese"] = "中文",
        ["LocEnglish"] = "English",
        ["LocWeeklyRemaining"] = "本周剩余",
        ["LocQuotaPace"] = "额度节奏",
        ["LocGeneralFiveHour"] = "5 小时额度",
        ["LocDay1"] = "第1天",
        ["LocDay2"] = "第2天",
        ["LocDay3"] = "第3天",
        ["LocDay4"] = "第4天",
        ["LocDay5"] = "第5天",
        ["LocDay6"] = "第6天",
        ["LocDay7"] = "第7天",
        ["LocSparkLimit"] = "Codex Spark 限额",
        ["LocFiveHourWindow"] = "5 小时窗口",
        ["LocWeeklyWindow"] = "每周窗口",
        ["LocResetCards"] = "重置卡",
        ["LocLocalAnalysis"] = "本地日志分析",
        ["LocCacheHit"] = "本地缓存命中",
        ["LocModelUsage"] = "模型用量",
        ["LocModelUsageDescription"] = "以下全部本地指标使用同一个所选时段；来自本机 rollout 样本，不计入官方总量，也不代表订阅账单。",
        ["LocToday"] = "今天",
        ["Loc7Days"] = "7 天",
        ["Loc30Days"] = "30 天",
        ["LocLocalRangeTotalTokens"] = "本地总 Token",
        ["LocCurrentEstimatedCost"] = "当前 API 等价成本（按实际缓存价）",
        ["LocCacheSavings"] = "使用缓存约节省：",
        ["LocCostWithoutCaching"] = "不使用缓存时的 API 等价成本（同等 Token）",
        ["LocCostWithoutCachingHelp"] = "仅将缓存输入改按普通输入价；Token 总量、输出和模型组合不变。基于公开 API 单价的情景估算，不是订阅账单。",
        ["LocModelRanking"] = "本地样本模型排行",
        ["LocNoModelUsage"] = "这个时间段还没有本地模型用量。",
        ["LocUsageComposition"] = "本地样本组成",
        ["LocHistoryTrends"] = "历史趋势",
        ["LocHistoryDescription"] = "按月或自定义日期查看官方日用量；本机 rollout 样本成本始终独立显示。",
        ["LocHistoryRange"] = "统计区间",
        ["LocHistoryMonthMode"] = "按月",
        ["LocHistoryCustomMode"] = "自定义",
        ["LocHistoryYear"] = "年份",
        ["LocHistoryMonth"] = "月份",
        ["LocHistoryStartDate"] = "开始日期",
        ["LocHistorySelectDate"] = "选择日期",
        ["LocHistoryEndDate"] = "结束日期",
        ["LocHistoryApplyRange"] = "应用区间",
        ["LocHistoryPreviousMonth"] = "上一个月",
        ["LocHistoryNextMonth"] = "下一个月",
        ["LocHistoryOfficialSummary"] = "官方区间统计",
        ["LocHistoryReturnedDays"] = "官方已返回天数",
        ["LocHistoryDailyAverage"] = "官方日均（仅返回日）",
        ["LocHistoryPeakDay"] = "官方峰值日",
        ["LocHistoryPeakTokens"] = "峰值 Tokens",
        ["LocHistoryLocalSample"] = "本机样本 API 等价成本",
        ["LocHistoryLocalDescription"] = "仅统计同一本地日历区间内的 rollout 样本；不计入官方合计，也不代表账单。",
        ["LocHistoryLocalTokens"] = "本机样本 Tokens",
        ["LocHistoryLocalCost"] = "约算成本",
        ["LocHistoryLocalCacheHit"] = "本机缓存命中",
        ["LocHistoryLocalCacheSavings"] = "本机缓存节省",
        ["LocHistoryDailyRange"] = "所选区间每日 Token · 官方",
        ["LocHistoryList"] = "列表",
        ["LocHistoryTrend"] = "趋势图",
        ["LocHistoryTrendHelp"] = "悬停查看详情；聚焦后用 ←/→、Home/End 选点。空白日期表示缺失，不是零。",
        ["LocHistoryNoOfficialDays"] = "所选区间暂无官方每日数据。缺失日期不会补零，也不会用本地样本填补。",
        ["LocMonthlyTokens"] = "官方本月 Tokens",
        ["LocOfficialRangeTokens"] = "官方 Tokens · 所选时段",
        ["LocDailyTokens"] = "本月每日 Token · 官方",
        ["LocDailyTokensDescription"] = "来自 account/usage/read；上方总量为以下官方每日数据之和。",
        ["LocHistoryPortable"] = "历史会随每次刷新写入本地数据库，换机时复制数据目录即可保留趋势。",
        ["LocOpenLocalDataFolder"] = "打开本地数据目录",
        ["LocDataFolderDescription"] = "数据库、价格快照与设置都保存在这里",
        ["LocBackOverview"] = "返回总览",
        ["LocBack"] = "返回",
        ["LocResetDetails"] = "重置卡详情",
        ["LocTimesAvailable"] = "次可用",
        ["LocValidityProgress"] = "有效期进度",
        ["LocGranted"] = "授予",
        ["LocCurrent"] = "当前",
        ["LocExpires"] = "到期",
        ["LocAvailableResetCards"] = "可用重置卡",
        ["LocResetHistory"] = "历史记录",
        ["LocResetHistoryDescription"] = "从首次运行开始记录；服务端缺少单卡详情时，使用与过期会标记为推测。",
        ["LocExpiryReminder"] = "到期前提醒",
        ["LocOpenCodexUsage"] = "打开 Codex 用量页面",
        ["LocOpenPanel"] = "打开面板",
        ["LocOpenPanelTooltip"] = "打开用量面板",
        ["LocRefreshNow"] = "立即刷新",
        ["LocRefreshNowTooltip"] = "立即刷新数据"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["LocAppTitle"] = "Codex Usage",
        ["LocTrayMenuTitle"] = "Codex Usage menu",
        ["LocMinimizeTooltip"] = "Minimize to tray",
        ["LocRefreshTooltip"] = "Refresh data",
        ["LocSettings"] = "Settings",
        ["LocUpdateAvailable"] = "Update available",
        ["LocUpdateNow"] = "View update",
        ["LocAutomaticUpdateChecks"] = "Automatically check for updates",
        ["LocAutomaticUpdateChecksTooltip"] = "Checks GitHub Releases at most once per day",
        ["LocCheckForUpdates"] = "Check for updates",
        ["LocNewVersionPublished"] = "A new version is available",
        ["LocViewUpdate"] = "View update",
        ["LocRemindLater"] = "Remind me later",
        ["LocClose"] = "Close",
        ["LocOverview"] = "Overview",
        ["LocModels"] = "Models",
        ["LocHistory"] = "History",
        ["LocLocalFirst"] = "Local first",
        ["LocFooterStatus"] = "Official totals · Local storage · 15 min refresh",
        ["LocCurrentVersion"] = "Current version",
        ["LocAutoRefresh"] = "Refreshes every 15 minutes",
        ["LocPricingCalibrated"] = "Prices checked at startup",
        ["LocOpenDataFolder"] = "Open data folder",
        ["LocData"] = "Data",
        ["LocQuitApplication"] = "Quit application",
        ["LocQuit"] = "Quit",
        ["LocAppearance"] = "Appearance",
        ["LocLight"] = "Light",
        ["LocDark"] = "Dark",
        ["LocStartup"] = "Start with Windows",
        ["LocStartupTooltip"] = "Start in the tray after signing in to Windows",
        ["LocLanguage"] = "Language",
        ["LocChinese"] = "中文",
        ["LocEnglish"] = "English",
        ["LocWeeklyRemaining"] = "Weekly remaining",
        ["LocQuotaPace"] = "Quota pace",
        ["LocGeneralFiveHour"] = "5-hour quota",
        ["LocDay1"] = "Day 1",
        ["LocDay2"] = "Day 2",
        ["LocDay3"] = "Day 3",
        ["LocDay4"] = "Day 4",
        ["LocDay5"] = "Day 5",
        ["LocDay6"] = "Day 6",
        ["LocDay7"] = "Day 7",
        ["LocSparkLimit"] = "Codex Spark limits",
        ["LocFiveHourWindow"] = "5-hour window",
        ["LocWeeklyWindow"] = "Weekly window",
        ["LocResetCards"] = "Reset credits",
        ["LocLocalAnalysis"] = "Local log analysis",
        ["LocCacheHit"] = "Local cache hit",
        ["LocModelUsage"] = "Model usage",
        ["LocModelUsageDescription"] = "Every local metric below uses the same selected period and comes from local rollout samples. It is not added to the official total or your subscription bill.",
        ["LocToday"] = "Today",
        ["Loc7Days"] = "7 days",
        ["Loc30Days"] = "30 days",
        ["LocLocalRangeTotalTokens"] = "Total local tokens",
        ["LocCurrentEstimatedCost"] = "Current API-equivalent cost (actual cached pricing)",
        ["LocCacheSavings"] = "Estimated savings with caching: ",
        ["LocCostWithoutCaching"] = "API-equivalent cost without caching (same tokens)",
        ["LocCostWithoutCachingHelp"] = "Only cached input is repriced at the standard input rate; token total, output, and model mix stay unchanged. This public API price scenario is not a subscription bill.",
        ["LocModelRanking"] = "Local sample model ranking",
        ["LocNoModelUsage"] = "No local model usage in this period.",
        ["LocUsageComposition"] = "Local sample mix",
        ["LocHistoryTrends"] = "Usage history",
        ["LocHistoryDescription"] = "View official daily usage by month or custom dates. Local rollout sample costs remain separate.",
        ["LocHistoryRange"] = "Statistics period",
        ["LocHistoryMonthMode"] = "By month",
        ["LocHistoryCustomMode"] = "Custom",
        ["LocHistoryYear"] = "Year",
        ["LocHistoryMonth"] = "Month",
        ["LocHistoryStartDate"] = "Start date",
        ["LocHistorySelectDate"] = "Choose date",
        ["LocHistoryEndDate"] = "End date",
        ["LocHistoryApplyRange"] = "Apply period",
        ["LocHistoryPreviousMonth"] = "Previous month",
        ["LocHistoryNextMonth"] = "Next month",
        ["LocHistoryOfficialSummary"] = "Official period statistics",
        ["LocHistoryReturnedDays"] = "Official days returned",
        ["LocHistoryDailyAverage"] = "Official daily average (returned days)",
        ["LocHistoryPeakDay"] = "Official peak day",
        ["LocHistoryPeakTokens"] = "Peak tokens",
        ["LocHistoryLocalSample"] = "Local sample API-equivalent cost",
        ["LocHistoryLocalDescription"] = "Rollout samples from the same local-calendar period only. They are not added to the official total and are not a bill.",
        ["LocHistoryLocalTokens"] = "Local sample tokens",
        ["LocHistoryLocalCost"] = "Estimated cost",
        ["LocHistoryLocalCacheHit"] = "Local cache hit",
        ["LocHistoryLocalCacheSavings"] = "Local cache savings",
        ["LocHistoryDailyRange"] = "Official daily tokens · Selected period",
        ["LocHistoryList"] = "List",
        ["LocHistoryTrend"] = "Trend chart",
        ["LocHistoryTrendHelp"] = "Hover for details; when focused, use ←/→ or Home/End. Gaps mean missing dates, not zero.",
        ["LocHistoryNoOfficialDays"] = "No official daily data in the selected period. Missing dates are neither filled with zero nor local samples.",
        ["LocMonthlyTokens"] = "Official tokens this month",
        ["LocOfficialRangeTokens"] = "Official tokens · Selected period",
        ["LocDailyTokens"] = "Official daily tokens this month",
        ["LocDailyTokensDescription"] = "From account/usage/read. The total above is the sum of these official daily values.",
        ["LocHistoryPortable"] = "Each refresh writes history to the local database. Copy the data folder to keep it when moving PCs.",
        ["LocOpenLocalDataFolder"] = "Open local data folder",
        ["LocDataFolderDescription"] = "Database, price snapshot, and settings are stored here",
        ["LocBackOverview"] = "Back to overview",
        ["LocBack"] = "Back",
        ["LocResetDetails"] = "Reset credit details",
        ["LocTimesAvailable"] = "available",
        ["LocValidityProgress"] = "Validity progress",
        ["LocGranted"] = "Granted",
        ["LocCurrent"] = "Now",
        ["LocExpires"] = "Expires",
        ["LocAvailableResetCards"] = "Available reset credits",
        ["LocResetHistory"] = "History",
        ["LocResetHistoryDescription"] = "Recorded from first run. Inferred use or expiry is marked when card details are unavailable.",
        ["LocExpiryReminder"] = "Expiry reminders",
        ["LocOpenCodexUsage"] = "Open Codex usage page",
        ["LocOpenPanel"] = "Open panel",
        ["LocOpenPanelTooltip"] = "Open usage panel",
        ["LocRefreshNow"] = "Refresh now",
        ["LocRefreshNowTooltip"] = "Refresh data now"
    };

    public static bool IsEnglish { get; private set; }

    public static string Get(string key, bool? isEnglish = null)
    {
        var source = (isEnglish ?? IsEnglish) ? English : Chinese;
        return source.TryGetValue(key, out var value) ? value : key;
    }

    public static void Apply(bool isEnglish)
    {
        IsEnglish = isEnglish;
        if (System.Windows.Application.Current is null)
        {
            return;
        }

        foreach (var (key, value) in isEnglish ? English : Chinese)
        {
            System.Windows.Application.Current.Resources[key] = value;
        }
    }
}
